/* ===================== DADOS ===================== */
const foods = [
  {n:"Arroz agulhinha (kg)", c:"Grãos e cereais", old:5.20, cur:5.53},
  {n:"Feijão carioca (kg)", c:"Grãos e cereais", old:8.40, cur:8.73},
  {n:"Feijão preto (kg)", c:"Grãos e cereais", old:9.10, cur:9.40},
  {n:"Farinha de mandioca (kg)", c:"Grãos e cereais", old:6.50, cur:6.30},
  {n:"Macarrão espaguete (500g)", c:"Grãos e cereais", old:4.20, cur:4.35},
  {n:"Tomate (kg)", c:"Hortifruti", old:6.80, cur:8.54},
  {n:"Cebola (kg)", c:"Hortifruti", old:5.50, cur:5.10},
  {n:"Batata inglesa (kg)", c:"Hortifruti", old:6.20, cur:5.80},
  {n:"Banana prata (kg)", c:"Hortifruti", old:4.80, cur:4.94},
  {n:"Laranja (kg)", c:"Hortifruti", old:3.90, cur:3.60},
  {n:"Cenoura (kg)", c:"Hortifruti", old:5.20, cur:5.60},
  {n:"Alface (unidade)", c:"Hortifruti", old:2.50, cur:2.70},
  {n:"Mandioca (kg)", c:"Hortifruti", old:4.50, cur:4.20},
  {n:"Abóbora (kg)", c:"Hortifruti", old:3.80, cur:4.00},
  {n:"Coco verde (unidade)", c:"Hortifruti", old:4.00, cur:4.50},
  {n:"Carne bovina 1ª (kg)", c:"Proteínas", old:38.90, cur:39.63},
  {n:"Frango inteiro (kg)", c:"Proteínas", old:9.80, cur:9.50},
  {n:"Ovos (dúzia)", c:"Proteínas", old:9.50, cur:10.20},
  {n:"Tilápia (kg)", c:"Proteínas", old:16.00, cur:15.20},
  {n:"Carne suína, pernil (kg)", c:"Proteínas", old:19.50, cur:20.30},
  {n:"Leite integral (litro)", c:"Laticínios", old:5.80, cur:6.01},
  {n:"Queijo coalho (kg)", c:"Laticínios", old:32.00, cur:33.50},
  {n:"Manteiga (200g)", c:"Laticínios", old:9.90, cur:10.04},
  {n:"Iogurte natural (170g)", c:"Laticínios", old:3.20, cur:3.35},
  {n:"Açúcar cristal (kg)", c:"Outros", old:4.60, cur:4.45},
  {n:"Café em pó (500g)", c:"Outros", old:22.00, cur:20.90},
  {n:"Óleo de soja (900ml)", c:"Outros", old:8.20, cur:7.90},
  {n:"Sal refinado (kg)", c:"Outros", old:2.30, cur:2.25},
  {n:"Pão francês (kg)", c:"Outros", old:14.50, cur:14.64},
  {n:"Margarina (500g)", c:"Outros", old:7.20, cur:7.45},
];

const markets = [
  {n:"Super Dabarra", addr:"Av. Pres. Castelo Branco, 4763 — Barra do Ceará", rating:4.3, tag:"Supermercado + padaria", lat:-3.7062508, lng:-38.574654, best:false},
  {n:"Supermercado Vinte", addr:"Av. 20 de Janeiro, 1680 — Barra do Ceará", rating:4.4, tag:"Mercantil tradicional", lat:-3.7057423, lng:-38.5812012, best:false},
  {n:"Atacadão LAG — Leste", addr:"Av. Pres. Castelo Branco, 5943 — Barra do Ceará", rating:4.3, tag:"Atacarejo", lat:-3.7023082, lng:-38.5842616, best:true},
  {n:"Mercadinho Super Aguiar", addr:"Tv. Castelo, 620 — Barra do Ceará", rating:4.2, tag:"Mercadinho de bairro", lat:-3.7007362, lng:-38.5825497, best:false},
  {n:"Mercadinho Teles", addr:"R. Graça Aranha, 397 — Barra do Ceará", rating:4.5, tag:"Mercadinho de bairro", lat:-3.7083534, lng:-38.5731151, best:false},
  {n:"Supermercado Kibão", addr:"Av. Pres. Castelo Branco, 5645 — Barra do Ceará", rating:4.4, tag:"Supermercado + entrega", lat:-3.7032269, lng:-38.5813109, best:false},
  {n:"Mercadinho Arco-Verde", addr:"R. 6 Companheiros, 262 — Barra do Ceará", rating:4.2, tag:"Mercadinho de bairro", lat:-3.7026790, lng:-38.5761454, best:false},
  {n:"Centerbox Barra do Ceará I", addr:"Av. Cel. Carvalho, 1261 — Barra do Ceará", rating:4.2, tag:"Rede de supermercados", lat:-3.7133333, lng:-38.5886111, best:true},
  {n:"Centerbox Barra do Ceará II", addr:"Av. Cel. Carvalho, 901 — Barra do Ceará", rating:4.2, tag:"Rede de supermercados", lat:-3.7099342, lng:-38.5889900, best:false},
  {n:"Mercadinho Cavalcante", addr:"R. Álvaro Garrido, 193 — Barra do Ceará", rating:4.3, tag:"Miúda e Genilson", lat:-3.7129179, lng:-38.5810946, best:false},
  {n:"Feira Negra de Fortaleza", addr:"R. Astrogildo Fontoura — Barra do Ceará", rating:3.0, tag:"Feira / atacado", lat:-3.7121362, lng:-38.5833711, best:false},
  {n:"Feira das Goiabeiras", addr:"R. Sen. Robert Kennedy, 410 — Barra do Ceará (sábados)", rating:4.6, tag:"Feira livre", lat:-3.7037143, lng:-38.5789647, best:true},
  {n:"Cometa Supermercados — Castelo Branco", addr:"Av. Pres. Castelo Branco, 5211 — Barra do Ceará", rating:4.4, tag:"Rede de supermercados", lat:-3.7048575, lng:-38.5779713, best:false},
  {n:"Mercadinho Ideal", addr:"R. Manuel Moura, 180 — Barra do Ceará", rating:4.6, tag:"Mercadinho de bairro", lat:-3.7149602, lng:-38.5826226, best:false},
  {n:"Mercantil Morros", addr:"R. Sen. Robert Kennedy, 209 — Barra do Ceará", rating:4.3, tag:"Mercantil de bairro", lat:-3.7017921, lng:-38.5778668, best:false},
];

const faqs = [
  {q:"De onde vêm os preços do site?", a:"Os valores partem de cotações públicas da Ceasa-CE e da Pesquisa Nacional da Cesta Básica (Dieese/Conab) para Fortaleza, e são refinados com reportes enviados por moradores da Barra do Ceará na aba Reportar."},
  {q:"Os preços são exatos, iguais ao caixa do mercado?", a:"Não necessariamente. Eles são valores de referência e podem variar de mercado para mercado e de um dia para o outro. Use o site para ter uma noção de tendência (alta ou queda) e sempre confirme o valor final no caixa."},
  {q:"Com que frequência os preços são atualizados?", a:"A base de referência é revisada mensalmente. Já os reportes da comunidade (aba Reportar) aparecem em tempo real, assim que são enviados."},
  {q:"Posso reportar um preço mesmo sem me identificar?", a:"Sim. O campo de nome é opcional — você pode enviar como anônimo ou usar um apelido."},
  {q:"Como reporto um produto perto do vencimento?", a:"Vá até a aba Reportar, clique em \"Reportar vencimento\", selecione o mercado e informe o produto e a data. Isso ajuda outros moradores a evitarem comprar produtos vencidos ou aproveitarem promoções de véspera de vencimento."},
  {q:"O Radar da Barra tem alguma ligação com os mercados listados?", a:"Não. É um projeto comunitário e independente. Os mercados são listados apenas como referência de localização para os moradores do bairro."},
];
